version: '3'
services:
    python-api:
        build: python/ .
        container_name: python-api
        ports:
            - "5000:5000"
    vue-ui:
        build: vue/ .
        container_name: vue-ui
        ports:
            - "8080:8080"
        depends_on: 
            - python-api
        